
package Forms;


import ChangePassword.ChangePassword;
import Companies.CompaniesPanel;
import Createuser.CreateUser;
import Forms.Product.ProductPanel;
import NewSalesRecord.NewSalesRecord;
import ProductCategory.AddCategory;
import SalesRecord.SalesRecord;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.TableColumn;
import net.proteanit.sql.DbUtils;
public class MainPanel extends javax.swing.JFrame  {
Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;


   
    public MainPanel() {
        initComponents();
        conn = ConnectionToDatabase.connectToDb();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        updateTable();
     
        
    }
     public void close(){
        WindowEvent we = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
 
    private void updateTable(){
   
        try{
          String sql = "SELECT  product_name as 'Product Name',company_name as 'Company Name',product_category as 'Product Category',quantity as 'Quantity',price_per_unit as 'Price Per Unit' FROM products";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            medicineTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        loggedInAsLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicineTable = new javax.swing.JTable();
        medicineBtn = new javax.swing.JButton();
        companiesBtn = new javax.swing.JButton();
        viewSalesRecordsBtn = new javax.swing.JButton();
        newSalesBtn = new javax.swing.JButton();
        changePasswordBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        createUserBtn = new javax.swing.JButton();
        addNewProductCategoryBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        searchTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
        });
        getContentPane().add(searchTxt);
        searchTxt.setBounds(429, 195, 314, 23);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("You're are logged in as :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1016, 198, 134, 17);

        loggedInAsLbl.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        loggedInAsLbl.setForeground(new java.awt.Color(153, 0, 0));
        loggedInAsLbl.setText("You're are logged in as :");
        getContentPane().add(loggedInAsLbl);
        loggedInAsLbl.setBounds(1160, 198, 134, 17);
        loggedInAsLbl.getAccessibleContext().setAccessibleDescription("");

        medicineTable.setBackground(new java.awt.Color(255, 51, 51));
        medicineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        medicineTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(medicineTable);
        medicineTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(326, 272, 991, 402);

        medicineBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        medicineBtn.setText("Product");
        medicineBtn.setIconTextGap(20);
        medicineBtn.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Drug-basket-icon.png"))); // NOI18N
        medicineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineBtnActionPerformed(evt);
            }
        });
        getContentPane().add(medicineBtn);
        medicineBtn.setBounds(10, 272, 237, 33);

        companiesBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        companiesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/companies-icon.png"))); // NOI18N
        companiesBtn.setText("Companies");
        companiesBtn.setIconTextGap(20);
        companiesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companiesBtnActionPerformed(evt);
            }
        });
        getContentPane().add(companiesBtn);
        companiesBtn.setBounds(10, 327, 237, 41);

        viewSalesRecordsBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        viewSalesRecordsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/sales-report-icon.png"))); // NOI18N
        viewSalesRecordsBtn.setText("Delete Buy Record");
        viewSalesRecordsBtn.setIconTextGap(20);
        viewSalesRecordsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSalesRecordsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewSalesRecordsBtn);
        viewSalesRecordsBtn.setBounds(10, 437, 237, 33);

        newSalesBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        newSalesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/shop-cart-add-icon.png"))); // NOI18N
        newSalesBtn.setText("Purchase/Buy");
        newSalesBtn.setIconTextGap(20);
        newSalesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSalesBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newSalesBtn);
        newSalesBtn.setBounds(10, 386, 237, 33);

        changePasswordBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        changePasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Apps-system-software-update-icon.png"))); // NOI18N
        changePasswordBtn.setText("Change Password");
        changePasswordBtn.setIconTextGap(20);
        changePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordBtnActionPerformed(evt);
            }
        });
        getContentPane().add(changePasswordBtn);
        changePasswordBtn.setBounds(10, 539, 237, 33);

        logOutBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        logOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Apps-session-logout-icon.png"))); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.setIconTextGap(20);
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logOutBtn);
        logOutBtn.setBounds(10, 653, 237, 33);

        createUserBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        createUserBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Actions-list-add-user-icon.png"))); // NOI18N
        createUserBtn.setText("Create User");
        createUserBtn.setIconTextGap(20);
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });
        getContentPane().add(createUserBtn);
        createUserBtn.setBounds(10, 602, 237, 33);

        addNewProductCategoryBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addNewProductCategoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/category-item-icon.png"))); // NOI18N
        addNewProductCategoryBtn.setText("Add New Product Category");
        addNewProductCategoryBtn.setIconTextGap(20);
        addNewProductCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewProductCategoryBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addNewProductCategoryBtn);
        addNewProductCategoryBtn.setBounds(10, 488, 237, 33);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Search Product");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(326, 198, 85, 17);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Application Icon/paint.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 21, 275, 219);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 51));
        jLabel5.setText("Paint Shop Management System");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(326, 79, 319, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\html\\bbb.jpg")); // NOI18N
        jLabel6.setText("mm");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-40, -10, 1540, 850);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void medicineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineBtnActionPerformed
          ProductPanel mp = new ProductPanel();
        close();
        mp.setVisible(true);
    }//GEN-LAST:event_medicineBtnActionPerformed

    private void companiesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companiesBtnActionPerformed
        CompaniesPanel cp = new CompaniesPanel();
        close();
        cp.setVisible(true);
    }//GEN-LAST:event_companiesBtnActionPerformed

    private void viewSalesRecordsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSalesRecordsBtnActionPerformed
        SalesRecord sr = new SalesRecord();
        close();
        sr.setVisible(true);
    }//GEN-LAST:event_viewSalesRecordsBtnActionPerformed

    private void newSalesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSalesBtnActionPerformed
        NewSalesRecord nsr =  new NewSalesRecord();
        close();
        nsr.setVisible(true);
    }//GEN-LAST:event_newSalesBtnActionPerformed

    private void changePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordBtnActionPerformed
        ChangePassword cp = new ChangePassword();
        close();
        cp.setVisible(true);
    }//GEN-LAST:event_changePasswordBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        Log l  = new Log();
        close();
        l.setVisible(true);
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
        CreateUser cu = new CreateUser();
        close();
        cu.setVisible(true);
    }//GEN-LAST:event_createUserBtnActionPerformed

    private void addNewProductCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewProductCategoryBtnActionPerformed
           AddCategory ac = new AddCategory();
           ac.setVisible(true);
    }//GEN-LAST:event_addNewProductCategoryBtnActionPerformed

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
              try{
          String sql = "SELECT  product_name as 'Product Name',company_name as 'Company Name',product_category as 'Product Category',quantity as 'Quantity',price_per_unit as 'Price Per Unit' FROM products WHERE product_name LIKE '%"+ searchTxt.getText() +"%'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            medicineTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_searchTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               /* if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewProductCategoryBtn;
    private javax.swing.JButton changePasswordBtn;
    private javax.swing.JButton companiesBtn;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOutBtn;
    public javax.swing.JLabel loggedInAsLbl;
    private javax.swing.JButton medicineBtn;
    private javax.swing.JTable medicineTable;
    private javax.swing.JButton newSalesBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JButton viewSalesRecordsBtn;
    // End of variables declaration//GEN-END:variables
}
